### ISSUE TITLE
Rank hands

### ISSUE THREAD

**Issue by Dreamey8** [townteki/townsquare#1048] opened 2021-09-19 16:49 UTC
Can we please have the rank hands easily visible in the game. Even if it is a pop up. So that people can use just the online and know the hand ranks as they are deciding on cards.

**Comment by mmeldo** [comment] 2021-09-19 19:21
Duplicate of #1049 
I am closing this so @Dreamey8 and @tybar both have one new issue opened 😄

**Closed by mmeldo** 2021-09-19 19:21 UTC
Labels: duplicate
