### ISSUE TITLE
Morgan Gadgetorium Does Not React Prior to the Start of Game

### ISSUE THREAD

**Issue by Huffster** [townteki/townsquare#1068] opened 2021-09-22 00:14 UTC
**Card**
Morgan Gadgetorium

**Describe the bug**
With Post-A-Tron in the starting posse the react should occur when inventing.

**To Reproduce**
1. Do action '...'
3. Start shootout '....'

**Screenshots**

**Additional context**

**Comment by mmeldo** [comment] 2021-09-22 03:05
Duplicate of issue #947

**Closed** 2021-09-22 03:06 UTC
Labels: duplicate
