### ISSUE TITLE
Eagle Woman That All Look At's ability doesn't work in shootout

### ISSUE THREAD

**Issue by anthony-colpron** [townteki/townsquare#1575] opened 2023-04-01 04:34 UTC
**Card**
Eagle Woman That All Look At

**Describe the bug**
When in a shootout, it is not possible for other shamans to use the ability bestowed by Eagle Woman That All Look at. 

**To Reproduce**
1. Have Eagle Woman That All Look At in play.
2. Start a shootout with another shaman inside
3. During shootout play, right click the shaman
4. The "use ability" button is disabled. It should be enabled, as it is during noon plays.

**Screenshots**

**Additional context**
I didn't test a lot. But I encountered the bug on a shaman that had another noon ability (Mazatl) that I had already used during the day.

**Comment by mmeldo** [comment] 2023-04-01 10:08
@anthony-colpron I do not see any mention of the required cost of booting a spirit. You sure there was a spirit in the Mazatl's location to boot?
Because I did a set of tests, some with Mazatl and it worked exactly as expected. Even booting totems at the location and even if Mazatl's ability was already used.
Thus I will need to ask you to please recreate it, and also post a screenshot.

**Comment by mmeldo** [comment] 2023-08-27 19:32
Closing as not reproduced

**Closed by mmeldo** 2023-08-27 19:32 UTC
Labels: bug :bug:, not-reproduced
