### ISSUE TITLE
Yunxu Jiang does not apply bullet bonus

### ISSUE THREAD

**Issue by anthony-colpron** [townteki/townsquare#1425] opened 2022-04-29 23:45 UTC
**Card**
Yunxu Jiang

**Describe the bug**
Yunxu Jiang's trait states:
> While Yunxu Jiang is in a shootout at a location you control, each of your other dudes in the posse gets +1 bullets and +1 value.

However, the bullet bonus is not applied, only the value bonus.

**To Reproduce**
1. Start a shootout with Yunxu Jiang and another dude at a location you control.
2. Observe that only the value of the other dude gets a +1, not their bullets.

**Comment by mmeldo** [comment] 2022-08-02 08:38
Me and @PesiTheWizard have tried to reproduce but could not. In my tests, the bullet bonus was applied correctly. Therefore either there was another effect preventing the bullet bonus, or there was some other condition necessary to reproduce the problem. That is why it is always good to add a screenshot which can tell us more.

**Comment by mmeldo** [comment] 2022-09-06 07:08
Closing, not able to reproduce.

**Closed by mmeldo** 2022-09-06 07:08 UTC
Labels: bug :bug:, not-reproduced
